using System;
using System.Collections.Generic;
using avvaunity.GOH.Unity.Message.Unmarshaller;

namespace namespaceBar {

    // Code generated by osc-proto (version 🧨) DO NOT EDIT.

    public readonly struct Foo {
        private readonly bool _fieldFoo;
        private readonly int _fieldBar;

        public Foo(bool fieldFoo, int fieldBar) {
            _fieldFoo = fieldFoo;
            _fieldBar = fieldBar;
        }

        public bool FieldFoo() {
            return _fieldFoo;
        }

        public int FieldBar() {
            return _fieldBar;
        }
    }

    public class FooUnmarshaller {

        // <fieldFoo:bool>
        // <fieldBar:int32>
        public Foo Unmarshal(List<object> data) {
            if (data.Count != 2) {
                throw new ArgumentException($"Expected 2 item in arg list but got {data.Count}");
            }
            var fieldFoo = ParseBool(data[0].ToString());
            var fieldBar = int.Parse(data[1].ToString());
            return new Foo(fieldFoo, fieldBar);
        }

        private static bool ParseBool(string value) {
            try {
                return int.Parse(value) != 0;
            }
            catch (Exception e) {
                throw new ArgumentException($"cannot parse {value} to bool", e);
            }
        }
    }
}
