using System;
using System.Collections.Generic;

namespace namespaceBar {

    // Code generated by osc-proto (version unknown) DO NOT EDIT.

    public readonly struct Bar {}

    public class BarUnmarshaller {

        public Bar Unmarshal(List<object> data) {
            if (data.Count != 0) {
                throw new ArgumentException($"Expected 0 item in arg list but got {data.Count}");
            }
            return new Bar();
        }

        private static bool ParseBool(string value) {
            try {
                return int.Parse(value) != 0;
            }
            catch (Exception e) {
                throw new ArgumentException($"cannot parse {value} to bool", e);
            }
        }
    }
}
