package golang_test

import (
	"testing"

	"github.com/glynternet/osc-proto/pkg/generate/generatetest"
	"github.com/glynternet/osc-proto/pkg/generate/golang"
	"github.com/glynternet/osc-proto/pkg/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestEmptyTypesShouldYieldEmptyFile(t *testing.T) {
	in := types.Types{}
	var expected map[string][]byte
	out, err := golang.Generator{}.Generate(in)
	require.NoError(t, err)
	assert.Equal(t, expected, out)
}

func TestVersionCommentShouldBePopulated(t *testing.T) {
	in := types.Types{
		"foo": {{
			FieldName: "fieldFoo",
			FieldType: "fieldFooType",
		}},
	}
	const expected = `package packageBar

// Code generated by osc-proto (version 🧨) DO NOT EDIT.

func FooMessageArgs(fieldFoo bool) []interface{} {
	return []interface{}{
		boolInt32(fieldFoo),
	}
}

// boolInt32 returns an int32 representation of a bool.
// This is required for supporting OSC frameworks that
// don't support a boolean primitive
func boolInt32(value bool) int32 {
	if value {
		return 1
	}
	return 0
}
`
	out, err := golang.Generator{
		OSCProtoVersion: "\U0001F9E8",
		Package:         "packageBar",
	}.Generate(in)
	require.NoError(t, err)
	generatetest.AssertEqualContentLayout(t, map[string]string{
		"packageBar.go": expected,
	}, out)
}

func TestSingleTypeShouldYieldResult(t *testing.T) {
	in := types.Types{
		"foo": {{
			FieldName: "fieldFoo",
			FieldType: "fieldFooType",
		}, {
			FieldName: "fieldBar",
			FieldType: "fieldBarType",
		}, {
			FieldName: "fieldBaz",
			FieldType: "fieldBazType",
		}},
	}
	const expected = `package packageBar

// Code generated by osc-proto (version unknown) DO NOT EDIT.

func FooMessageArgs(fieldFoo bool, fieldBar bool, fieldBaz bool) []interface{} {
	return []interface{}{
		boolInt32(fieldFoo),
		boolInt32(fieldBar),
		boolInt32(fieldBaz),
	}
}

// boolInt32 returns an int32 representation of a bool.
// This is required for supporting OSC frameworks that
// don't support a boolean primitive
func boolInt32(value bool) int32 {
	if value {
		return 1
	}
	return 0
}
`
	out, err := golang.Generator{Package: "packageBar"}.Generate(in)
	require.NoError(t, err)
	generatetest.AssertEqualContentLayout(t, map[string]string{
		"packageBar.go": expected,
	}, out)
}

func TestMultipleTypesShouldYieldUResult(t *testing.T) {
	in := types.Types{
		"foo": {},
		"bar": {{
			FieldName: "fieldBar",
			FieldType: "fieldBarType",
		}},
	}

	const fooExpected = `package packageName

// Code generated by osc-proto (version unknown) DO NOT EDIT.

func BarMessageArgs(fieldBar bool) []interface{} {
	return []interface{}{
		boolInt32(fieldBar),
	}
}

func FooMessageArgs() []interface{} {
	return []interface{}{
	}
}

// boolInt32 returns an int32 representation of a bool.
// This is required for supporting OSC frameworks that
// don't support a boolean primitive
func boolInt32(value bool) int32 {
	if value {
		return 1
	}
	return 0
}
`
	out, err := golang.Generator{
		Package: "packageName",
	}.Generate(in)
	require.NoError(t, err)
	generatetest.AssertEqualContentLayout(t, map[string]string{
		"packageName.go": fooExpected,
	}, out)
}
